Extended library with Information about "responses" w/ type information
wcandillon/swagger-js-codegen pull request #163
Opened 2017-01-14 02:03 UTC by bradleat

Adding onto #127 we now have type information on the {{responses}} object.

2017-01-17 20:21 UTC, bradleat commented
Also added optional parameters to typescript definitions

2017-01-18 08:22 UTC, wcandillon commented
@bradleat: Is there an example I could look at?

2017-03-16 05:32 UTC, bradleat commented
@wcandillon apologies. Is the example still needed?

What would you want to see? A source spec and a template that makes use of the new variables?

2017-03-16 07:47 UTC, wcandillon commented on lib/typescript.js
> +            // see if property is required
This change and the one in `type.mustache` seems to be unrelated to the other change with the response, is my understanding correct?

2017-03-16 07:47 UTC, wcandillon approved these changes

2017-03-28 18:01 UTC, bradleat commented on lib/typescript.js
> +            // see if property is required
It is. I think you have the correct understanding.

One goal was to give in response type information to the templates.

The other goal was to add the information about optional properties

2017-05-09 14:30 UTC, Fcena commented
Hi guys,

When will this PR get merged? What is the current status of it? 
I really need this feature.

Best Regards

2017-05-09 16:05 UTC, fantun3s requested changes

2017-05-09 16:05 UTC, Fcena commented on lib/typescript.js
> +
This _forEach should replace the above one, otherwise, it will result in duplicated typescript properties.

2025-06-08 08:31 UTC, closed without merging